# typed.js 动效参数；时间单位均为毫秒。
typed.typeSpeed=39
typed.backSpeed=26
typed.backDelay=2700
typed.startDelay=350
typed.smartBackspace=false
typed.loop=true
typed.cursorChar=▍

# 三月七角色语录；通过 quote.<序号> 控制播放顺序。
quote.1=可爱即是正义！
quote.2=本姑娘出马，怎么可能会输嘛~
quote.3=照相机才是我的本体。
quote.4=左青龙，右白虎，少吃碳水化合物——看招！
quote.5=是时候展现真正的剑术了。
quote.6=我是被遗忘的过去，是陪伴『她』的长夜。
quote.7=又见到你了，真好。
quote.8=走过的路，总要留个纪念~
